services:
  app:
    image: file-manager:reactive
    container_name: file-manager-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "6"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data

volumes:
    data:
      {}