services:
  app:
    image: file-manager:synchronous
    container_name: file-manager-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "4"
        reservations:
          memory: 4G
          cpus: "2"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:fmdb
      SPRING_DATASOURCE_USERNAME: deniz
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx6g -XX:MaxMetaspaceSize=512m -Djava.util.concurrent.ForkJoinPool.common.parallelism=4"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: thomseno/h2
    container_name: h2-database
    ports:
      - "8082:8082"