services:
  app:
    image: file-manager:synchronous
    container_name: file-manager-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: "3"
        reservations:
            memory: 3G
            cpus: "1.5"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:fmdb
      SPRING_DATASOURCE_USERNAME: deniz
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JAVA_TOOL_OPTIONS: "-Xms1g -Xmx8g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -XX:ParallelGCThreads=2 -XX:ConcGCThreads=1"
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: thomseno/h2
    container_name: h2-database
    ports:
      - "8082:8082"