services:
  app:
    image: file-manager:reactive
    container_name: file-manager-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "6"
    networks:
      - file-manager-network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - file-manager-network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
    {}
networks:
  file-manager-network:
    driver: bridge